name: Infrastructure CI


on:
  push:
    branches:
      - main
      - master

  pull_request:
    branches:
      - main
      - master



jobs:

  # ==================================================
  # Job 1: Docker Validation & Build Check
  # ==================================================

  docker-check:

    name: Docker Lint & Build

    runs-on: ubuntu-latest


    steps:

      - name: Checkout Repository
        uses: actions/checkout@v4



      - name: Run Hadolint Backend Dockerfile
        if: exists('backend/Dockerfile')
        uses: hadolint/hadolint-action@v3.1.0
        with:
          dockerfile: ./backend/Dockerfile
        continue-on-error: true



      - name: Build Backend Docker Image
        run: |
          if [ -f "./backend/Dockerfile" ]; then
            docker build \
              -t mern-backend:test \
              ./backend
          else
            echo "Backend Dockerfile not found - skipping"
          fi



      - name: Build Frontend Docker Image
        run: |
          if [ -f "./frontend/Dockerfile" ]; then
            docker build \
              -t mern-frontend:test \
              ./frontend
          else
            echo "Frontend Dockerfile not found - skipping"
          fi





  # ==================================================
  # Job 2: Terraform Validation
  # ==================================================

  terraform-validate:

    name: Terraform Check

    runs-on: ubuntu-latest


    defaults:
      run:
        working-directory: ./terraform/environments/local


    steps:

      - name: Checkout Repository
        uses: actions/checkout@v4



      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: "1.5.0"



      - name: Terraform Init
        run: terraform init -backend=false



      - name: Terraform Format Check
        run: terraform fmt -check -recursive



      - name: Terraform Validate
        run: terraform validate





  # ==================================================
  # Job 3: Kubernetes Configuration Validation
  # ==================================================

  kubernetes-validate:

    name: Kubernetes Manifest Check

    runs-on: ubuntu-latest


    steps:


      - name: Checkout Repository
        uses: actions/checkout@v4



      - name: Setup kubectl
        uses: azure/setup-kubectl@v4
        with:
          version: latest



      - name: Create Dummy Environment File
        run: |
          mkdir -p k8s/overlays/local

          cat <<EOF > k8s/overlays/local/.env
          DB_PASSWORD=dummy
          MONGO_URL=mongodb://dummy
          EOF



      - name: Validate Kustomize Build
        run: |
          kubectl kustomize k8s/overlays/local



      - name: Validate Kubernetes Manifests
        run: |
          kubectl kustomize k8s/overlays/local \
          | kubectl apply --dry-run=client -f -
